version: '3'

services:
  pap:
    container_name: argus-pap.cnaf.test
    hostname: argus-pap
    domainname: cnaf.test
    build: ./pap/
    image: argus-pap-el7
    ports:
      - "8150:8150"
      - "8151:8150"
      - "9012:9012"
      - "4002:4002"
    volumes:
      - /dev/urandom:/dev/random
      - ${ARGUS_DEV_PAP}:/opt/code/argus-pap:ro
      - ${ARGUS_DEV_DOT_JREBEL}:/root/.jrebel:rw
      - ${ARGUS_DEV_JREBEL}:/opt/jrebel:ro
      - ${ARGUS_DEV_HOSTCERT_PEM}:/etc/grid-security/hostcert.pem:ro
      - ${ARGUS_DEV_HOSTKEY_PEM}:/etc/grid-security/hostkey.pem:ro
      - ${ARGUS_DEV_PUPPET_ARGUS}:/opt/argus-mw-devel:ro
      - /home/marco/workspace/scratch/trust-anchors:/etc/grid-security/certificates
    environment:
      TZ: Europe/Rome
      ENABLE_JREBEL: y
      ENABLE_JMX: y
      JMX_PORT: 9012
      ENABLE_DEBUG: y
      DEBUG_PORT: 4002
      FACTER_ARGUS_REPO_BASE_URL: ${FACTER_ARGUS_REPO_BASE_URL}

  pdp:
    container_name: argus-pdp.cnaf.test
    hostname: argus-pdp
    domainname: cnaf.test
    build: ./pdp/
    image: argus-pdp-el7
    ports:
      - "8152:8152"
      - "8153:8153"
      - "9011:9011"
      - "4001:4001"
    depends_on:
      - pap
    volumes:
      - /dev/urandom:/dev/random
      - ${ARGUS_DEV_PDP}:/opt/code/argus-pdp:ro
      - ${ARGUS_DEV_DOT_JREBEL}:/root/.jrebel:rw
      - ${ARGUS_DEV_JREBEL}:/opt/jrebel:ro
      - ${ARGUS_DEV_HOSTCERT_PEM}:/etc/grid-security/hostcert.pem:ro
      - ${ARGUS_DEV_HOSTKEY_PEM}:/etc/grid-security/hostkey.pem:ro
      - ${ARGUS_DEV_PUPPET_ARGUS}:/opt/argus-mw-devel:ro
      - /home/marco/workspace/scratch/trust-anchors:/etc/grid-security/certificates
    environment:
      TZ: Europe/Rome
      ENABLE_JREBEL: y
      ENABLE_JMX: y
      JMX_PORT: 9011
      ENABLE_DEBUG: y
      DEBUG_PORT: 4001
      PAP_HOST: argus-pap.cnaf.test
      PAP_PORT: 8150
      FACTER_ARGUS_REPO_BASE_URL: ${FACTER_ARGUS_REPO_BASE_URL}

  pep:
    container_name: argus-pep.cnaf.test
    hostname: argus-pep
    domainname: cnaf.test
    build: ./pep/
    image: argus-pep-el7
    ports:
      - "8154:8154"
      - "8155:8155"
      - "9010:9010"
      - "4000:4000"
    depends_on:
      - pdp
      - oidc-client
    volumes:
      - /dev/urandom:/dev/random
      - ${ARGUS_DEV_PEPD}:/opt/code/argus-pep-server:ro
      - ${ARGUS_DEV_DOT_JREBEL}:/root/.jrebel:rw
      - ${ARGUS_DEV_JREBEL}:/opt/jrebel:ro
      - ${ARGUS_DEV_HOSTCERT_PEM}:/etc/grid-security/hostcert.pem:ro
      - ${ARGUS_DEV_HOSTKEY_PEM}:/etc/grid-security/hostkey.pem:ro
      - ${ARGUS_DEV_PROXY_DIR}:/proxies:ro
      - ${ARGUS_DEV_PUPPET_ARGUS}:/opt/argus-mw-devel:ro
      - /home/marco/workspace/scratch/trust-anchors:/etc/grid-security/certificates
    environment:
      TZ: Europe/Rome
      ENABLE_JREBEL: y
      ENABLE_JMX: y
      JMX_PORT: 9010
      ENABLE_DEBUG: y
      DEBUG_PORT: 4000
      PDP_HOST: argus-pdp.cnaf.test
      PDP_PORT: 8152
      FACTER_ARGUS_REPO_BASE_URL: ${FACTER_ARGUS_REPO_BASE_URL}

#  bdii:
#    container_name: argus-bdii.cnaf.test
#    hostname: argus-bdii
#    domainname: cnaf.test
#    build: ./bdii/
#    image: argus-bdii-el7
#    ports:
#      - "2170:2170"
#    depends_on:
#      - pap
#      - pdp
#      - pep
#    volumes:
#      - ~/workspace/argus-mw-devel:/opt/argus-mw-devel:ro

  oidc-client:
    container_name: argus-oidc.cnaf.test
    hostname: argus-oidc
    domainname: cnaf.test
    build: ./oidc-client/
    image: argus-oidc-client-el7
    ports:
      - "8156:8156"
      - "4003:4003"
    volumes:
      - /dev/urandom:/dev/random
      - ${ARGUS_DEV_OIDC_CLIENT}:/opt/code/argus-oidc-client:ro
      - /home/marco/workspace/scratch/trust-anchors:/etc/grid-security/certificates
    environment:
      TZ: Europe/Rome
      IAM_BASE_URL: https://iam.local.io
      IAM_CLIENT_ID: argus-oidc-client-id
      IAM_CLIENT_SECRET: argus-oidc-client-secret
      ENABLE_DEBUG: y
      DEBUG_PORT: 4003
      DEBUG_SUSPEND: n

networks:
  default:
    external:
      name: iam_default
